### ISSUE TITLE
new version has some issues with selection of directory

### ISSUE THREAD

**Issue by noxnoire** [lReDragol/OnceHuman_PhotoChanger#3]
when u choose a wrong folder theres no check in as for is it the correct folder?
also after selecting it cannot be reselected again?

**Comment by tsoul1** [comment]
"As a temporary solution, you can check the 'config.json' file located in the temp folder path specified in the console debug window. If you delete that file and run the application again, the path will be reset."

**Comment by tsoul1** [comment]
"The 'photo' path should be set to 'Documents' > 'res' > 'photo_local' within the folder where the game is installed.

As for the 'video' path, I'm not sure. As a temporary measure, you can set it to any location. From my experience, photos are updated correctly when using this method."

**Comment by noxnoire** [comment]
for video in case of a single disk/partition machine default should be "C:\Program Files (x86)\Steam\steamapps\common\Once Human\res\environment\dynamic_objects\buildingsystem\facility\wishmachine\texture\wishmachine.mp4" which idk why doesnt automatically check that directory but does a "for drive in (insert all possible drive letter)"
edit , it actually check for a file on video but the prompt doesnt verify its a correct directory

**Comment by lReDragol** [comment]
> for video in case of a single disk/partition machine default should be "C:\Program Files (x86)\Steam\steamapps\common\Once Human\res\environment\dynamic_objects\buildingsystem\facility\wishmachine\texture\wishmachine.mp4" which idk why doesnt automatically check that directory but does a "for drive in (insert all possible drive letter)" edit , it actually check for a file on video but the prompt doesnt verify its a correct directory

Hi.
My search is piled on the folders [(f'{drive}:', 'SteamLibrary', 'steamapps', 'common', 'Once Human', 'res', 'environment', 'dynamic_objects', 'buildingsystem', 'facility', 'wishmachine', 'texture', 'wishmachine.mp4')] and starts with 'SteamLibrary' as it is supposed to be at all but you do not have it so the code and did not search further on the disk.
In the next update (it will be big) I will take into account your variant of location.
Thanks for letting me know.

**Comment by Chen169792** [comment]
appreciate redrgo good work i also same problem cannot be reselected is it blocked? or still working
![ex](https://github.com/user-attachments/assets/c0dc536b-47f1-4c23-beea-0949168dd2d5)

**Comment by tsoul1** [comment]
"Please review the comments to ensure that the correct paths have been set properly."

**Comment by tsoul1** [comment]
"Please review the comments to ensure that the correct paths have been set properly."

**Comment by tsoul1** [comment]
> redrgo 좋은 작업에 감사드립니다. 저도 같은 문제가 있는데 다시 선택할 수 없습니다. 차단된 건가요? 아니면 아직 작동 중인 건가요? ![전- ](https://private-user-images.githubusercontent.com/180207741/364097383-c0dc536b-47f1-4c23-beea-0949168dd2d5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU0MzE5NTIsIm5iZiI6MTcyNTQzMTY1MiwicGF0aCI6Ii8xODAyMDc3NDEvMzY0MDk3MzgzLWMwZGM1MzZiLTQ3ZjEtNGMyMy1iZWVhLTA5NDkxNjhkZDJkNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwNFQwNjM0MTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03NDY0Zjk2ZTQ0OTAxNjI0ZTNmNzdkZjlkNmRmOGYyNTdiNTA3NjcxZDQ3NDQwYjNiYWZkNzZjMTU4MzE2NzMyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.TMRKiC42_x7aO8JEkpD_CE4kaFMCepKe32TfTGctkAM)

"Please review the comments to ensure that the correct paths have been set properly."

**Comment by sx66627** [comment]
> appreciate redrgo good work i also same problem cannot be reselected is it blocked? or still working ![ex](https://private-user-images.githubusercontent.com/180207741/364097383-c0dc536b-47f1-4c23-beea-0949168dd2d5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY1NjI5OTEsIm5iZiI6MTcyNjU2MjY5MSwicGF0aCI6Ii8xODAyMDc3NDEvMzY0MDk3MzgzLWMwZGM1MzZiLTQ3ZjEtNGMyMy1iZWVhLTA5NDkxNjhkZDJkNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxN1QwODQ0NTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hMDMwMWU2NWE3YzE2OTZhNzdlOWJhZWIyNTNjN2RhNDJiMWM3ZWFlNWNhYWViYjRhYzIxZWFlY2YwZDczN2VlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.RjmGKVaOkwwKwL8o-RAlr-dkvy1Qsv_Jq3TxhDzYHlI)

Подтверждаю, не работает. При запуске на win 11 от локального пользователя ошибка:
`Translations loaded.
Temporary folder created: C:\Users\Chudik\AppData\Local\Temp\Temp_Once_Human_Change
Config loaded.
Temporary folder created: C:\Users\Chudik\AppData\Local\Temp\Temp_Once_Human_Change
Icon path for usa_flag.png: C:\Users\Chudik\AppData\Local\Temp\_MEI669962\icons\usa_flag.png
Icon path for russia_flag.png: C:\Users\Chudik\AppData\Local\Temp\_MEI669962\icons\russia_flag.png
Application started.
Console hidden after delay.
Console shown.
File dropped: C:/Users/Chudik/Desktop/human_capture.png
Processing image: C:/Users/Chudik/Desktop/human_capture.png
Image does not need resizing: C:/Users/Chudik/Desktop/human_capture.png
Image displayed on canvas.
Paths verified.
Template set: C:/Users/Chudik/Desktop/human_capture.png
File observer started at: M:SteamLibrary\steamapps\common\Once Human\Documents\res\photo_local
File created: M:SteamLibrary\steamapps\common\Once Human\Documents\res\photo_local\photo20240917084631.png
Exception in thread Thread-1:
Traceback (most recent call last):
  File "threading.py", line 1052, in _bootstrap_inner
  File "watchdog\observers\api.py", line 223, in run
  File "watchdog\observers\api.py", line 402, in dispatch_events
  File "watchdog\events.py", line 224, in dispatch
  File "main.py", line 92, in on_created
PermissionError: [WinError 5] Отказано в доступе: 'M:SteamLibrary\\steamapps\\common\\Once Human\\Documents\\res\\photo_local\\photo20240917084631.png'`

А если запускать от админа, то не перетащить изображение на окно программы.
@lReDragol Вопрос, неужели нельзя писать программы по человечески?? Почему нет кнопки открыть файл?

**Comment by lReDragol** [comment]
> > appreciate redrgo good work i also same problem cannot be reselected is it blocked? or still working ![ex](https://private-user-images.githubusercontent.com/180207741/364097383-c0dc536b-47f1-4c23-beea-0949168dd2d5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY1NjI5OTEsIm5iZiI6MTcyNjU2MjY5MSwicGF0aCI6Ii8xODAyMDc3NDEvMzY0MDk3MzgzLWMwZGM1MzZiLTQ3ZjEtNGMyMy1iZWVhLTA5NDkxNjhkZDJkNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxN1QwODQ0NTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hMDMwMWU2NWE3YzE2OTZhNzdlOWJhZWIyNTNjN2RhNDJiMWM3ZWFlNWNhYWViYjRhYzIxZWFlY2YwZDczN2VlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.RjmGKVaOkwwKwL8o-RAlr-dkvy1Qsv_Jq3TxhDzYHlI)
> 
> Подтверждаю, не работает. При запуске на win 11 от локального пользователя ошибка: `Translations loaded. Temporary folder created: C:\Users\Chudik\AppData\Local\Temp\Temp_Once_Human_Change Config loaded. Temporary folder created: C:\Users\Chudik\AppData\Local\Temp\Temp_Once_Human_Change Icon path for usa_flag.png: C:\Users\Chudik\AppData\Local\Temp\_MEI669962\icons\usa_flag.png Icon path for russia_flag.png: C:\Users\Chudik\AppData\Local\Temp\_MEI669962\icons\russia_flag.png Application started. Console hidden after delay. Console shown. File dropped: C:/Users/Chudik/Desktop/human_capture.png Processing image: C:/Users/Chudik/Desktop/human_capture.png Image does not need resizing: C:/Users/Chudik/Desktop/human_capture.png Image displayed on canvas. Paths verified. Template set: C:/Users/Chudik/Desktop/human_capture.png File observer started at: M:SteamLibrary\steamapps\common\Once Human\Documents\res\photo_local File created: M:SteamLibrary\steamapps\common\Once Human\Documents\res\photo_local\photo20240917084631.png Exception in thread Thread-1: Traceback (most recent call last): File "threading.py", line 1052, in _bootstrap_inner File "watchdog\observers\api.py", line 223, in run File "watchdog\observers\api.py", line 402, in dispatch_events File "watchdog\events.py", line 224, in dispatch File "main.py", line 92, in on_created PermissionError: [WinError 5] Отказано в доступе: 'M:SteamLibrary\\steamapps\\common\\Once Human\\Documents\\res\\photo_local\\photo20240917084631.png'`
> 
> А если запускать от админа, то не перетащить изображение на окно программы. @lReDragol Вопрос, неужели нельзя писать программы по человечески?? Почему нет кнопки открыть файл?

Ответ довольно прост :)
Я банально не планировал делать из обычного скрипта мини пролижение.
Изначально скрипт для замены фото я делал для себя и никого больше но мои соклановци попросили сделать им так же но не все умеют работать с консолью поэтому мне пришлось сделать самую бональную менюшку с минимальным функционалом.
 Но из за того что даная прога ушла за пределы клана и люди начали писать об ошибках (а я на такое вообще не расчитывал) пришлось выкатывать фиксы в виде версии 0.2 и 0.3. 
 Сейчас же я решился серьёздно взятся за доработку и внедрение новых функций дабы сделать полноценную тулзу в которой уже будет сделано всё как положено.
![изображение_2024-09-17_173758485](https://github.com/user-attachments/assets/80614027-0168-4c7c-aeea-88f491f5fe14)
Если ты жожешь или знаешь кого то кто может помочь с реверс инжинирингом игры то обнову получится выкатить быстрее с наименьшим количеством багов.
В ближайшее время постораюсь выкатить beta версию (скрин).

**Comment by fieelk** [comment]
the photo I'm adding is not being verified. Writes "The image could not be verified, viewing is not possible"
Don't know how to fix it? What am I doing wrong?
